Attribute VB_Name = "constant"
Public Const intRowsNum1 As Integer = 1
Public Const strMessage1 As String = "すべてのファイル名を変更完了"
Public Const strErrMessage1 As String = "一部のファイル名を変更出来ません"
Public Const strErrMessage2 As String = "ファイル名マスターシートをご確認ください"
Public Const strErrMessage3 As String = "異常が発生したため、処理を終了いたします。"
Public Const strErrMessage4 As String = "エラー内容"
Public Const strErrMessage5 As String = "フォルダパスを指定してください"
Public Const strErrMessage6 As String = "フォルダパスが存在しません"
Public Const strEvaluation1 As String = "OK"
Public Const strEvaluation2 As String = "NG"
Public Const strBlank As String = ""
Public Const strDollarMark As String = "\"
Public Const strDotMark As String = "."

